# Default values for fetch-tweets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ragatzino/twitter-api-python-fetcher:latest
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

subject: ukraine
secretname:
  bearer: <no-token-provided>
schedule: "0 0 * * 0"
