apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-tweets
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: Ragatzino/fetch-tweets:latest
            imagePullPolicy: IfNotPresent
            command:
            - python main.py
            envFrom:
            - secretRef:
                name: fetch-tweets
            - configMapRef:
                name: fetch-tweets
          restartPolicy: OnFailure
